sudo: false
language: python
branches:
  only:
  - master
  - develop
os:
  - linux
python:
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.7"
  - "3.8-dev"
  - "nightly"
before_script:  # commands to run before running tests
  - "$TRAVIS_BUILD_DIR/tests/init"
script:
  - pytest -v
after_script:
  - rm -rf "$HOME/test-snotebooks"
env: 
  global:
    - SNOTE="$HOME/test-snotebooks/snoterc"
    - SNOTE_DEBUG=True
