#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys
import os
import logging
import datetime
import src.lib as lib
import tempfile
import subprocess
from subprocess import call
from src.lib import log

def main():
    args = lib.parse_commands()

    try:
        lib.validate_notebook(args.notebook)
    except lib.UnknownNotebookError as e:
        log.error('%s: I do not know that notebook', e)
        sys.exit(1)
    except lib.InvalidNotebookPathError:
        log.error('%s: Way to configure paths, slick', e)
        sys.exit(1)

    if args.subcommand == 'update':
        lib.update_note(args.notebook, args.filename, args.timestamp)

    if args.subcommand == 'new':
        lib.new_note(args.notebook, args.filename, args.timestamp)


if __name__ == '__main__':
    lib.print_header()
    main()
